### ISSUE TITLE
Improve UI/UX

### ISSUE THREAD

**Issue by cbrzn** [vocdoni/bridge-ui#36]
I would love to know what are your thoughts on this... I guess you might have some ideas on what to do - Just let me know :-D

**Comment by brickpop** [comment]
To start:

- [ ] Unify button style
- Wallet status (top right)
   - [ ] Show a connect button when not connected
   - [ ] Show a message when the eth chain is not the expected one
   - [ ] Show the address + identicon + disconnect when connected
